name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your main branch name
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # Change if deploying to a different branch
          folder: ./  # Path to your HTML files, assuming they are in the root

